//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarablesKIT.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarablesKIT.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay ähnelt.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Activity ähnelt.
        /// </summary>
        public static string AddActivityButton {
            get {
                return ResourceManager.GetString("AddActivityButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adding Activity ähnelt.
        /// </summary>
        public static string AddingActivity {
            get {
                return ResourceManager.GetString("AddingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and ähnelt.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coming soon ähnelt.
        /// </summary>
        public static string Coming_soon {
            get {
                return ResourceManager.GetString("Coming soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cool ähnelt.
        /// </summary>
        public static string Cool {
            get {
                return ResourceManager.GetString("Cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CountMode ähnelt.
        /// </summary>
        public static string CountModeNameLabel {
            get {
                return ResourceManager.GetString("CountModeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Activity ähnelt.
        /// </summary>
        public static string CurrentActivityUnbindedLabel {
            get {
                return ResourceManager.GetString("CurrentActivityUnbindedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t parse the given file! ähnelt.
        /// </summary>
        public static string DatabaseConnectionFileParseError {
            get {
                return ResourceManager.GetString("DatabaseConnectionFileParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t save the data! ähnelt.
        /// </summary>
        public static string DataBaseErrorFailedToSave {
            get {
                return ResourceManager.GetString("DataBaseErrorFailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path doesn&apos;t exist! ähnelt.
        /// </summary>
        public static string DataBaseFileDoesntExistError {
            get {
                return ResourceManager.GetString("DataBaseFileDoesntExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trainingsdata_EarblesKIT.txt ähnelt.
        /// </summary>
        public static string DataBaseStorageFileName {
            get {
                return ResourceManager.GetString("DataBaseStorageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Data ähnelt.
        /// </summary>
        public static string DataOverviewPageDeleteButton {
            get {
                return ResourceManager.GetString("DataOverviewPageDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to your Dataoverview ähnelt.
        /// </summary>
        public static string DataOverviewPageEntryLabel {
            get {
                return ResourceManager.GetString("DataOverviewPageEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        public static string DataOverviewPageExportButton {
            get {
                return ResourceManager.GetString("DataOverviewPageExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string DataOverviewPageImportButton {
            get {
                return ResourceManager.GetString("DataOverviewPageImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something went wrong! ähnelt.
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Activity ähnelt.
        /// </summary>
        public static string EditActivityButton {
            get {
                return ResourceManager.GetString("EditActivityButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the amount of repetitions ähnelt.
        /// </summary>
        public static string EnterRepetitions {
            get {
                return ResourceManager.GetString("EnterRepetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception! ähnelt.
        /// </summary>
        public static string ErrorAlert {
            get {
                return ResourceManager.GetString("ErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete trainingsdata ähnelt.
        /// </summary>
        public static string ImportExportDeleteDataButton {
            get {
                return ResourceManager.GetString("ImportExportDeleteDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export trainingsdata ähnelt.
        /// </summary>
        public static string ImportExportExportButton {
            get {
                return ResourceManager.GetString("ImportExportExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File couldn&apos;t get picked correctly! ähnelt.
        /// </summary>
        public static string ImportExportFileError {
            get {
                return ResourceManager.GetString("ImportExportFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import trainingsdata ähnelt.
        /// </summary>
        public static string ImportExportImportButton {
            get {
                return ResourceManager.GetString("ImportExportImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import/Export file needs to end with .txt ähnelt.
        /// </summary>
        public static string ImportExportInformationLabel {
            get {
                return ResourceManager.GetString("ImportExportInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datamanagement ähnelt.
        /// </summary>
        public static string ImportExportLabel {
            get {
                return ResourceManager.GetString("ImportExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Listen And Perform ähnelt.
        /// </summary>
        public static string ListenAndPerformNameLabel {
            get {
                return ResourceManager.GetString("ListenAndPerformNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are standing ähnelt.
        /// </summary>
        public static string MusicModeCurrentStatusLabelStanding {
            get {
                return ResourceManager.GetString("MusicModeCurrentStatusLabelStanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are walking ähnelt.
        /// </summary>
        public static string MusicModeCurrentStatusLabelWalking {
            get {
                return ResourceManager.GetString("MusicModeCurrentStatusLabelWalking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MusicMode ähnelt.
        /// </summary>
        public static string MusicModeEntryLabel {
            get {
                return ResourceManager.GetString("MusicModeEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wonderful MusicModeEntry page! ähnelt.
        /// </summary>
        public static string MusicModeEntryLabel1 {
            get {
                return ResourceManager.GetString("MusicModeEntryLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Activity, ähnelt.
        /// </summary>
        public static string NextActivity {
            get {
                return ResourceManager.GetString("NextActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Okay ähnelt.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Possible Activities ähnelt.
        /// </summary>
        public static string PossibleActivitiesLabel {
            get {
                return ResourceManager.GetString("PossibleActivitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Push-ups ähnelt.
        /// </summary>
        public static string Push_ups {
            get {
                return ResourceManager.GetString("Push-ups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PushUps ähnelt.
        /// </summary>
        public static string PushUps {
            get {
                return ResourceManager.GetString("PushUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Activity ähnelt.
        /// </summary>
        public static string RemoveActivityButton {
            get {
                return ResourceManager.GetString("RemoveActivityButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection failed! ähnelt.
        /// </summary>
        public static string ScanningPopUpAlertCouldntConnect {
            get {
                return ResourceManager.GetString("ScanningPopUpAlertCouldntConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No device connected! ähnelt.
        /// </summary>
        public static string ScanningPopUpAlertLabel {
            get {
                return ResourceManager.GetString("ScanningPopUpAlertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string ScanningPopUpCancelButton {
            get {
                return ResourceManager.GetString("ScanningPopUpCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        public static string ScanningPopUpConnectButton {
            get {
                return ResourceManager.GetString("ScanningPopUpConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location denied! ähnelt.
        /// </summary>
        public static string ScanningPopUpLocationDenied {
            get {
                return ResourceManager.GetString("ScanningPopUpLocationDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location permission is needed! ähnelt.
        /// </summary>
        public static string ScanningPopUpPermissionLocationNeeded {
            get {
                return ResourceManager.GetString("ScanningPopUpPermissionLocationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan Devices ähnelt.
        /// </summary>
        public static string ScanningPopUpScanDevicesButton {
            get {
                return ResourceManager.GetString("ScanningPopUpScanDevicesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bluetooth is not active! ähnelt.
        /// </summary>
        public static string ScanningPopUpTurnBluetoothOn {
            get {
                return ResourceManager.GetString("ScanningPopUpTurnBluetoothOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seconds ähnelt.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select an Activity: ähnelt.
        /// </summary>
        public static string SelectAnActivity {
            get {
                return ResourceManager.GetString("SelectAnActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string SettingsPageLanguage {
            get {
                return ResourceManager.GetString("SettingsPageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Samplingrate (Hz) ähnelt.
        /// </summary>
        public static string SettingsPageSamplingrate {
            get {
                return ResourceManager.GetString("SettingsPageSamplingrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string SettingsPageSave {
            get {
                return ResourceManager.GetString("SettingsPageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saved! ähnelt.
        /// </summary>
        public static string SettingsPageSavingDone {
            get {
                return ResourceManager.GetString("SettingsPageSavingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steplength (cm) ähnelt.
        /// </summary>
        public static string SettingsPageSteplength {
            get {
                return ResourceManager.GetString("SettingsPageSteplength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string SettingsPageUsername {
            get {
                return ResourceManager.GetString("SettingsPageUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving failed! Please check your inputs ähnelt.
        /// </summary>
        public static string SettingsPageWrongInput {
            get {
                return ResourceManager.GetString("SettingsPageWrongInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sit-ups ähnelt.
        /// </summary>
        public static string Sit_ups {
            get {
                return ResourceManager.GetString("Sit-ups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SitUps ähnelt.
        /// </summary>
        public static string SitUps {
            get {
                return ResourceManager.GetString("SitUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start CountMode ähnelt.
        /// </summary>
        public static string StartCountModeButton {
            get {
                return ResourceManager.GetString("StartCountModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Workout ähnelt.
        /// </summary>
        public static string StartWorkoutButton {
            get {
                return ResourceManager.GetString("StartWorkoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance Walked Last Time ähnelt.
        /// </summary>
        public static string StepModeLastDistanceLabel {
            get {
                return ResourceManager.GetString("StepModeLastDistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steps Taken Last Time ähnelt.
        /// </summary>
        public static string StepModeLastStepsLabel {
            get {
                return ResourceManager.GetString("StepModeLastStepsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StepMode ähnelt.
        /// </summary>
        public static string StepModeNameLabel {
            get {
                return ResourceManager.GetString("StepModeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Stepmode ähnelt.
        /// </summary>
        public static string StepModeStartButton {
            get {
                return ResourceManager.GetString("StepModeStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Started On/At ähnelt.
        /// </summary>
        public static string StepModeStartDataTime {
            get {
                return ResourceManager.GetString("StepModeStartDataTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop Stepmode ähnelt.
        /// </summary>
        public static string StepModeStopButton {
            get {
                return ResourceManager.GetString("StepModeStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Trainings Date ähnelt.
        /// </summary>
        public static string StepModeTrainingsDateLabel {
            get {
                return ResourceManager.GetString("StepModeTrainingsDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequency in Steps per Minute ähnelt.
        /// </summary>
        public static string StepModeUnbindedFrequencyLabel {
            get {
                return ResourceManager.GetString("StepModeUnbindedFrequencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Status ähnelt.
        /// </summary>
        public static string StepModeUnbindedStatusLabel {
            get {
                return ResourceManager.GetString("StepModeUnbindedStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steps Taken During This Session  ähnelt.
        /// </summary>
        public static string StepModeUnbindedStepsDoneLabel {
            get {
                return ResourceManager.GetString("StepModeUnbindedStepsDoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steps ähnelt.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop CountMode ähnelt.
        /// </summary>
        public static string StopCountModeButton {
            get {
                return ResourceManager.GetString("StopCountModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop Workout ähnelt.
        /// </summary>
        public static string StopWorkoutButton {
            get {
                return ResourceManager.GetString("StopWorkoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ukulele_low {
            get {
                return ResourceManager.GetStream("ukulele_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workout Plan ähnelt.
        /// </summary>
        public static string WorkoutPlanLabel {
            get {
                return ResourceManager.GetString("WorkoutPlanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have done ähnelt.
        /// </summary>
        public static string YouHaveDone {
            get {
                return ResourceManager.GetString("YouHaveDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have taken ähnelt.
        /// </summary>
        public static string YouHaveTaken {
            get {
                return ResourceManager.GetString("YouHaveTaken", resourceCulture);
            }
        }
    }
}
