
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarablesKIT.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarablesKIT.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wonderful DataOverviewPage! ähnelt.
        /// </summary>
        internal static string DataOverviewPageEntryLabel {
            get {
                return ResourceManager.GetString("DataOverviewPageEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wonderful MusicModeEntry page! ähnelt.
        /// </summary>
        internal static string MusicModeEntryLabel {
            get {
                return ResourceManager.GetString("MusicModeEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance Walked Last Time ähnelt.
        /// </summary>
        internal static string StepModeLastDistanceLabel {
            get {
                return ResourceManager.GetString("StepModeLastDistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steps Taken Last Time ähnelt.
        /// </summary>
        internal static string StepModeLastStepsLabel {
            get {
                return ResourceManager.GetString("StepModeLastStepsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StepMode ähnelt.
        /// </summary>
        internal static string StepModeNameLabel {
            get {
                return ResourceManager.GetString("StepModeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Stepmode ähnelt.
        /// </summary>
        internal static string StepModeStartButton {
            get {
                return ResourceManager.GetString("StepModeStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Started On/At ähnelt.
        /// </summary>
        internal static string StepModeStartDataTime {
            get {
                return ResourceManager.GetString("StepModeStartDataTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop Stepmode ähnelt.
        /// </summary>
        internal static string StepModeStopButton {
            get {
                return ResourceManager.GetString("StepModeStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Trainings Date ähnelt.
        /// </summary>
        internal static string StepModeTrainingsDateLabel {
            get {
                return ResourceManager.GetString("StepModeTrainingsDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequency in Steps per Minute ähnelt.
        /// </summary>
        internal static string StepModeUnbindedFrequencyLabel {
            get {
                return ResourceManager.GetString("StepModeUnbindedFrequencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Status ähnelt.
        /// </summary>
        internal static string StepModeUnbindedStatusLabel {
            get {
                return ResourceManager.GetString("StepModeUnbindedStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steps Taken During This Session  ähnelt.
        /// </summary>
        internal static string StepModeUnbindedStepsDoneLabel {
            get {
                return ResourceManager.GetString("StepModeUnbindedStepsDoneLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wonderful DataOverviewPage!.
        /// </summary>
        internal static string DataOverviewPageEntryLabel {
            get {
                return ResourceManager.GetString("DataOverviewPageEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception!.
        /// </summary>
        internal static string ErrorAlert {
            get {
                return ResourceManager.GetString("ErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wonderful MusicModeEntry page!.
        /// </summary>
        internal static string MusicModeEntryLabel {
            get {
                return ResourceManager.GetString("MusicModeEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
    }
}