//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarablesKIT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarablesKIT.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wonderful DataOverviewPage!.
        /// </summary>
        internal static string DataOverviewPageEntryLabel {
            get {
                return ResourceManager.GetString("DataOverviewPageEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception!.
        /// </summary>
        internal static string ErrorAlert {
            get {
                return ResourceManager.GetString("ErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wonderful MusicModeEntry page!.
        /// </summary>
        internal static string MusicModeEntryLabel {
            get {
                return ResourceManager.GetString("MusicModeEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wonderful MusicModeEntry page!.
        /// </summary>
        internal static string MusicModeEntryLabel1 {
            get {
                return ResourceManager.GetString("MusicModeEntryLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsPageLanguage {
            get {
                return ResourceManager.GetString("SettingsPageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samplingrate.
        /// </summary>
        internal static string SettingsPageSamplingrate {
            get {
                return ResourceManager.GetString("SettingsPageSamplingrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsPageSave {
            get {
                return ResourceManager.GetString("SettingsPageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steplength.
        /// </summary>
        internal static string SettingsPageSteplength {
            get {
                return ResourceManager.GetString("SettingsPageSteplength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string SettingsPageUsername {
            get {
                return ResourceManager.GetString("SettingsPageUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Walked Last Time.
        /// </summary>
        internal static string StepModeLastDistanceLabel {
            get {
                return ResourceManager.GetString("StepModeLastDistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps Taken Last Time.
        /// </summary>
        internal static string StepModeLastStepsLabel {
            get {
                return ResourceManager.GetString("StepModeLastStepsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepMode.
        /// </summary>
        internal static string StepModeNameLabel {
            get {
                return ResourceManager.GetString("StepModeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Stepmode.
        /// </summary>
        internal static string StepModeStartButton {
            get {
                return ResourceManager.GetString("StepModeStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Started On/At.
        /// </summary>
        internal static string StepModeStartDataTime {
            get {
                return ResourceManager.GetString("StepModeStartDataTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Stepmode.
        /// </summary>
        internal static string StepModeStopButton {
            get {
                return ResourceManager.GetString("StepModeStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Trainings Date.
        /// </summary>
        internal static string StepModeTrainingsDateLabel {
            get {
                return ResourceManager.GetString("StepModeTrainingsDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency in Steps per Minute.
        /// </summary>
        internal static string StepModeUnbindedFrequencyLabel {
            get {
                return ResourceManager.GetString("StepModeUnbindedFrequencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        internal static string StepModeUnbindedStatusLabel {
            get {
                return ResourceManager.GetString("StepModeUnbindedStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps Taken During This Session .
        /// </summary>
        internal static string StepModeUnbindedStepsDoneLabel {
            get {
                return ResourceManager.GetString("StepModeUnbindedStepsDoneLabel", resourceCulture);
            }
        }
    }
}
